services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    networks:
      pihole_network:
        ipv4_address: '192.168.0.150' #update IP
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    environment:
      TZ: 'Europe/London'
      WEBPASSWORD: '8574@Pihole@' #update password
    volumes:
      - '/home/djb66/Docker/Apps/pihole/etc-pihole:/etc/pihole' #update location
      - '/home/djb66/Docker/Apps/pihole/etc-dnsmasq.d:/etc/dnsmasq.d' #update location
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

networks:
  pihole_network:
    driver: macvlan
    driver_opts:
      parent: eth0 #update ethernet adapter
    ipam:
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1
