version: '3'
services:
    watchtower:
        image: containrrr/watchtower
        container_name: watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - TZ=Australia/Sydney
            - WATCHTOWER_DISABLE_CONTAINERS:=it-tools cloudflare-ddns nextcloud-aio-watchtower nextcloud-aio-mastercontainer nextcloud-aio-collabora nextcloud-aio-talk nextcloud-aio-database nextcloud-aio-redis nextcloud-aio-fulltextsearch nextcloud-aio-talk-recording nextcloud-aio-imaginary nextcloud-aio-nextcloud nextcloud-aio-notify-push
            - WATCHTOWER_MONITOR_ONLY=true
            - WATCHTOWER_SCHEDULE=0 0 16 ? * THU
            - WATCHTOWER_CLEANUP=true
            - WATCHTOWER_NOTIFICATIONS=email
            - WATCHTOWER_NOTIFICATION_EMAIL_FROM=davidbooby@gmail.com
            - WATCHTOWER_NOTIFICATION_EMAIL_TO=djboob66@tpg.com.au
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtp.gmail.com
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=rchu higl fcfl pkno 
            - WATCHTOWER_NOTIFICATION_EMAIL_SUBJECTTAG=Pi5-nas Server Container Updates
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=davidbooby@gmail.com
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587
            - WATCHTOWER_NOTIFICATIONS_HOSTNAME=Pi5-nas

        restart: unless-stopped
		